version: '3.11'

services:
  djangoapp:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Attendence_System
      - sqlite_data:/Attendence_System/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1 # Set to 0 in production

volumes:
  sqlite_data: